FROM node:20

WORKDIR /app

COPY backend/package*.json ./backend/
RUN npm install --prefix backend

COPY backend/ ./backend/

RUN cd backend && npx prisma generate

RUN npm run bundle --prefix backend

EXPOSE 5000

CMD ["sh", "-c", "cd /app/backend && npx prisma migrate deploy && npm start"]
